import React from 'react';
import { Box, Button, Chip, IconButton, InputAdornment, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField, Tooltip, Typography } from '@mui/material';
import SearchRoundedIcon from '@mui/icons-material/SearchRounded';
import AddRoundedIcon from '@mui/icons-material/AddRounded';
import EditRoundedIcon from '@mui/icons-material/EditRounded';
import DeleteOutlineRoundedIcon from '@mui/icons-material/DeleteOutlineRounded';
import { finalSinIva, formatPrice, normalizeText } from '../lib/catalogUtils.js';
import ProductDialog from './ProductDialog.jsx';
export default function ProductsView({products,onSave,onDelete}){const [q,setQ]=React.useState('');const [page,setPage]=React.useState(0);const [rows,setRows]=React.useState(25);const [edit,setEdit]=React.useState(undefined);const [open,setOpen]=React.useState(false);const filtered=React.useMemo(()=>products.filter(p=>!q||normalizeText(`${p.codigo} ${p.nombre} ${p.rubro} ${p.seccion}`).includes(normalizeText(q))),[products,q]);const visible=filtered.slice(page*rows,page*rows+rows);const close=()=>{setOpen(false);setEdit(undefined)};return <Stack spacing={2.5}><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" alignItems={{md:'end'}} gap={2}><Box><Typography variant="h4">Productos</Typography><Typography color="text.secondary" sx={{mt:.7}}>Buscá un producto y editá solamente lo que necesites.</Typography></Box><Button variant="contained" startIcon={<AddRoundedIcon/>} onClick={()=>{setEdit(undefined);setOpen(true)}}>Nuevo producto</Button></Stack><TextField fullWidth value={q} onChange={e=>{setQ(e.target.value);setPage(0)}} placeholder="Buscar por código, producto o rubro…" InputProps={{startAdornment:<InputAdornment position="start"><SearchRoundedIcon/></InputAdornment>}}/><TableContainer component={Paper} variant="outlined"><Table><TableHead><TableRow><TableCell>Código</TableCell><TableCell>Producto</TableCell><TableCell>Rubro</TableCell><TableCell align="right">Stock</TableCell><TableCell align="right">Precio s/IVA</TableCell><TableCell align="right">Acciones</TableCell></TableRow></TableHead><TableBody>{visible.map(p=><TableRow key={p.id||`${p.codigo}-${p.nombre}-${p.presentacion}`} hover><TableCell><Chip label={p.codigo} size="small" variant="outlined"/></TableCell><TableCell><Typography fontWeight={800}>{p.nombre}</Typography><Typography variant="caption" color="text.secondary">{p.presentacion||'Sin presentación'}</Typography></TableCell><TableCell>{p.rubro}</TableCell><TableCell align="right">{p.stock===null?'Consultar':p.stock}</TableCell><TableCell align="right"><Typography fontWeight={800}>{formatPrice(finalSinIva(p))}</Typography></TableCell><TableCell align="right"><Tooltip title="Editar"><IconButton onClick={()=>{setEdit(p);setOpen(true)}}><EditRoundedIcon/></IconButton></Tooltip><Tooltip title="Eliminar"><IconButton color="error" onClick={()=>{if(confirm(`¿Eliminar ${p.codigo} - ${p.nombre}?`))onDelete(p.id)}}><DeleteOutlineRoundedIcon/></IconButton></Tooltip></TableCell></TableRow>)}</TableBody></Table><TablePagination component="div" count={filtered.length} page={page} onPageChange={(_,p)=>setPage(p)} rowsPerPage={rows} onRowsPerPageChange={e=>{setRows(Number(e.target.value));setPage(0)}} rowsPerPageOptions={[25,50,100]} labelRowsPerPage="Mostrar" labelDisplayedRows={({from,to,count})=>`${from}-${to} de ${count}`}/></TableContainer><ProductDialog open={open} product={edit} onClose={close} onSave={async p=>{await onSave(p);close()}}/></Stack>}
