import React from 'react';
import { Alert, Badge, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Drawer, FormControl, IconButton, InputAdornment, InputLabel, MenuItem, Paper, Select, Stack, TextField, Typography } from '@mui/material';
import SearchRoundedIcon from '@mui/icons-material/SearchRounded';
import ShoppingCartRoundedIcon from '@mui/icons-material/ShoppingCartRounded';
import AddRoundedIcon from '@mui/icons-material/AddRounded';
import RemoveRoundedIcon from '@mui/icons-material/RemoveRounded';
import DeleteOutlineRoundedIcon from '@mui/icons-material/DeleteOutlineRounded';
import WhatsAppIcon from '@mui/icons-material/WhatsApp';
import { CONTACT, finalConIva, formatPrice, normalizeText } from '../lib/catalogUtils.js';

export default function OrdersView({products,cart,setCart}){
 const [search,setSearch]=React.useState('');const [rubro,setRubro]=React.useState('');const [open,setOpen]=React.useState(false);const [checkout,setCheckout]=React.useState(false);const [customer,setCustomer]=React.useState({nombre:'',telefono:'',localidad:''});
 const rubros=React.useMemo(()=>[...new Set(products.map(p=>p.rubro).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')),[products]);
 const filtered=React.useMemo(()=>products.filter(p=>(!rubro||p.rubro===rubro)&&(!search||normalizeText(`${p.codigo} ${p.nombre} ${p.presentacion}`).includes(normalizeText(search)))).slice(0,120),[products,search,rubro]);
 const add=p=>setCart(prev=>{const productId=p.id||`${p.codigo}|${p.nombre}|${p.presentacion}`;const x=prev.find(i=>i.id===productId);return x?prev.map(i=>i.id===productId?{...i,cantidad:i.cantidad+1}:i):[...prev,{id:productId,codigo:p.codigo,nombre:p.nombre,presentacion:p.presentacion,cantidad:1,precio:finalConIva(p)}]});
 const units=cart.reduce((a,b)=>a+b.cantidad,0), total=cart.reduce((a,b)=>a+b.precio*b.cantidad,0);
 const send=()=>{const lines=cart.map(i=>`${i.codigo} - ${i.nombre} | Cant: ${i.cantidad} | ${formatPrice(i.precio*i.cantidad)}`).join('\n');const msg=`Hola POLCARFER, quiero solicitar este pedido.\n\nCliente: ${customer.nombre}\nTeléfono: ${customer.telefono}\nLocalidad: ${customer.localidad}\n\nPRODUCTOS\n${lines}\n\nTotal estimado c/IVA: ${formatPrice(total)}\n\nPor favor confirmar disponibilidad, precio vigente y entrega.`;window.open(`https://wa.me/${CONTACT.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank','noopener');setCheckout(false);};
 return <Stack spacing={2.5}>
  <Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" alignItems={{md:'end'}} gap={2}><Box><Typography variant="h4">Armar pedido</Typography><Typography color="text.secondary" sx={{mt:.7}}>Elegí productos y cantidades. El pedido se envía a la distribuidora para confirmación.</Typography></Box><Badge badgeContent={units} color="primary"><Button variant="contained" startIcon={<ShoppingCartRoundedIcon/>} onClick={()=>setOpen(true)}>Ver pedido</Button></Badge></Stack>
  <Alert severity="info" variant="outlined">Los importes son orientativos hasta que POLCARFER confirme disponibilidad y condiciones comerciales.</Alert>
  <Paper variant="outlined" sx={{p:2}}><Stack direction={{xs:'column',md:'row'}} gap={1.5}><TextField fullWidth value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto…" InputProps={{startAdornment:<InputAdornment position="start"><SearchRoundedIcon/></InputAdornment>}}/><FormControl sx={{minWidth:{md:250}}}><InputLabel>Rubro</InputLabel><Select value={rubro} label="Rubro" onChange={e=>setRubro(e.target.value)}><MenuItem value="">Todos</MenuItem>{rubros.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl></Stack></Paper>
  <Stack spacing={1}>{filtered.map(p=><Paper key={p.id||`${p.codigo}-${p.nombre}-${p.presentacion}`} variant="outlined" sx={{p:2}}><Stack direction={{xs:'column',sm:'row'}} alignItems={{sm:'center'}} gap={2}><Box sx={{flex:1,minWidth:0}}><Stack direction="row" spacing={1} alignItems="center"><Chip label={p.codigo} size="small" variant="outlined"/><Typography fontWeight={800} noWrap>{p.nombre}</Typography></Stack><Typography variant="body2" color="text.secondary" sx={{mt:.5}}>{p.presentacion||p.rubro}</Typography></Box><Box sx={{minWidth:150}}><Typography variant="caption" color="text.secondary">Precio c/IVA</Typography><Typography fontWeight={900}>{formatPrice(finalConIva(p))}</Typography></Box><Button variant="outlined" startIcon={<AddRoundedIcon/>} onClick={()=>add(p)} disabled={p.stock!==null&&p.stock<=0}>Agregar</Button></Stack></Paper>)}</Stack>
  <Drawer anchor="right" open={open} onClose={()=>setOpen(false)} PaperProps={{sx:{width:{xs:'100%',sm:430},p:3}}}><Stack spacing={2} sx={{height:'100%'}}><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h5">Tu pedido</Typography><Chip label={`${units} unidades`}/></Stack><Box sx={{flex:1,overflow:'auto'}}>{cart.length?cart.map(i=><Paper key={i.id} variant="outlined" sx={{p:1.7,mb:1.2}}><Typography fontWeight={800}>{i.nombre}</Typography><Typography variant="caption" color="text.secondary">{i.codigo} · {formatPrice(i.precio)} c/u</Typography><Stack direction="row" alignItems="center" spacing={1} sx={{mt:1.3}}><IconButton size="small" onClick={()=>setCart(c=>c.map(x=>x.id===i.id?{...x,cantidad:Math.max(1,x.cantidad-1)}:x))}><RemoveRoundedIcon/></IconButton><Typography>{i.cantidad}</Typography><IconButton size="small" onClick={()=>setCart(c=>c.map(x=>x.id===i.id?{...x,cantidad:x.cantidad+1}:x))}><AddRoundedIcon/></IconButton><Box sx={{flex:1}}/><Typography fontWeight={800}>{formatPrice(i.precio*i.cantidad)}</Typography><IconButton size="small" onClick={()=>setCart(c=>c.filter(x=>x.id!==i.id))}><DeleteOutlineRoundedIcon/></IconButton></Stack></Paper>):<Box sx={{py:8,textAlign:'center'}}><ShoppingCartRoundedIcon sx={{fontSize:52,color:'text.secondary'}}/><Typography fontWeight={800} sx={{mt:2}}>Todavía no agregaste productos</Typography></Box>}</Box><Stack spacing={1.5}><Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Total estimado</Typography><Typography variant="h6">{formatPrice(total)}</Typography></Stack><Button size="large" variant="contained" disabled={!cart.length} onClick={()=>{setOpen(false);setCheckout(true)}}>Continuar</Button></Stack></Stack></Drawer>
  <Dialog open={checkout} onClose={()=>setCheckout(false)} fullWidth maxWidth="sm"><DialogTitle>Datos para enviar el pedido</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><TextField label="Nombre / Razón social" value={customer.nombre} onChange={e=>setCustomer({...customer,nombre:e.target.value})}/><TextField label="Teléfono" value={customer.telefono} onChange={e=>setCustomer({...customer,telefono:e.target.value})}/><TextField label="Localidad" value={customer.localidad} onChange={e=>setCustomer({...customer,localidad:e.target.value})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setCheckout(false)}>Cancelar</Button><Button variant="contained" startIcon={<WhatsAppIcon/>} disabled={!customer.nombre||!customer.telefono} onClick={send}>Enviar por WhatsApp</Button></DialogActions></Dialog>
 </Stack>;
}
