import React from 'react';
import { Box, Button, Chip, FormControl, InputAdornment, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField, Typography } from '@mui/material';
import SearchRoundedIcon from '@mui/icons-material/SearchRounded';
import DownloadRoundedIcon from '@mui/icons-material/DownloadRounded';
import { exportExcel, finalConIva, finalSinIva, formatPrice, normalizeText } from '../lib/catalogUtils.js';

export default function PriceListView({products}){
 const [search,setSearch]=React.useState(''); const [rubro,setRubro]=React.useState(''); const [page,setPage]=React.useState(0); const [rows,setRows]=React.useState(25);
 const rubros=React.useMemo(()=>[...new Set(products.map(p=>p.rubro).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')),[products]);
 const filtered=React.useMemo(()=>products.filter(p=>(!rubro||p.rubro===rubro)&&(!search||normalizeText(`${p.codigo} ${p.nombre} ${p.presentacion} ${p.seccion}`).includes(normalizeText(search)))),[products,search,rubro]);
 React.useEffect(()=>setPage(0),[search,rubro]);
 const visible=filtered.slice(page*rows,page*rows+rows);
 return <Stack spacing={2.5}>
  <Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" alignItems={{md:'end'}} gap={2}><Box><Typography variant="h4">Lista de precios</Typography><Typography color="text.secondary" sx={{mt:.7}}>Buscá un producto y revisá sus precios. Los descuentos ya están aplicados.</Typography></Box><Button variant="outlined" startIcon={<DownloadRoundedIcon/>} onClick={()=>exportExcel(products)}>Descargar lista Excel</Button></Stack>
  <Paper variant="outlined" sx={{p:2}}><Stack direction={{xs:'column',md:'row'}} gap={1.5}><TextField fullWidth value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por código, producto o medida…" InputProps={{startAdornment:<InputAdornment position="start"><SearchRoundedIcon/></InputAdornment>}}/><FormControl sx={{minWidth:{md:250}}}><InputLabel>Rubro</InputLabel><Select value={rubro} label="Rubro" onChange={e=>setRubro(e.target.value)}><MenuItem value="">Todos los rubros</MenuItem>{rubros.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl></Stack></Paper>
  <Typography variant="body2" color="text.secondary">{filtered.length.toLocaleString('es-AR')} productos encontrados</Typography>
  <TableContainer component={Paper} variant="outlined"><Table><TableHead><TableRow><TableCell>Código</TableCell><TableCell>Producto</TableCell><TableCell>Presentación</TableCell><TableCell align="right">Precio s/IVA</TableCell><TableCell align="right">Precio c/IVA</TableCell></TableRow></TableHead><TableBody>{visible.map(p=><TableRow hover key={p.id||`${p.codigo}-${p.nombre}-${p.presentacion}`}><TableCell><Chip label={p.codigo} size="small" variant="outlined"/></TableCell><TableCell><Stack spacing={.4}><Typography fontWeight={750}>{p.nombre}</Typography><Stack direction="row" spacing={1} alignItems="center"><Typography variant="caption" color="text.secondary">{p.rubro}</Typography>{p.tieneDescuento&&<Chip label={`-${Math.round(p.descuento*100)}%`} size="small" color="success"/>}</Stack></Stack></TableCell><TableCell>{p.presentacion||'—'}</TableCell><TableCell align="right"><Typography fontWeight={800}>{formatPrice(finalSinIva(p))}</Typography></TableCell><TableCell align="right"><Typography fontWeight={800}>{formatPrice(finalConIva(p))}</Typography></TableCell></TableRow>)}{!visible.length&&<TableRow><TableCell colSpan={5}><Box sx={{py:6,textAlign:'center'}}><Typography fontWeight={700}>No encontramos productos</Typography><Typography color="text.secondary">Probá con otra palabra o quitá el filtro.</Typography></Box></TableCell></TableRow>}</TableBody></Table><TablePagination component="div" count={filtered.length} page={page} onPageChange={(_,p)=>setPage(p)} rowsPerPage={rows} onRowsPerPageChange={e=>{setRows(Number(e.target.value));setPage(0)}} rowsPerPageOptions={[25,50,100]} labelRowsPerPage="Mostrar" labelDisplayedRows={({from,to,count})=>`${from}-${to} de ${count}`}/></TableContainer>
 </Stack>;
}
